/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class najkraciputevi_BellmanFordAlgorithm */

#ifndef _Included_najkraciputevi_BellmanFordAlgorithm
#define _Included_najkraciputevi_BellmanFordAlgorithm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     najkraciputevi_BellmanFordAlgorithm
 * Method:    runAlgorithmNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_najkraciputevi_BellmanFordAlgorithm_runAlgorithmNative
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
