/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class najkraciputevi_FloydWarshallAlgorithm */

#ifndef _Included_najkraciputevi_FloydWarshallAlgorithm
#define _Included_najkraciputevi_FloydWarshallAlgorithm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     najkraciputevi_FloydWarshallAlgorithm
 * Method:    runAlgorithmNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_najkraciputevi_FloydWarshallAlgorithm_runAlgorithmNative
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
