/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class najkraciputevi_DijkstraAlgorithm */

#ifndef _Included_najkraciputevi_DijkstraAlgorithm
#define _Included_najkraciputevi_DijkstraAlgorithm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     najkraciputevi_DijkstraAlgorithm
 * Method:    runAlgorithmNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_najkraciputevi_DijkstraAlgorithm_runAlgorithmNative
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
