/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package najkraciputevi;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;


/**
 *
 * @author winco
 */
public class Gui extends javax.swing.JFrame {
    /**
     * Creates new form Gui
     */
    Database db;
    public Gui() {
        this.db = new Database();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        us_neus = new javax.swing.ButtonGroup();
        fileChooser = new javax.swing.JFileChooser();
        krivibroj = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        vercnt = new javax.swing.JTextField();
        brojvrhovalabel = new javax.swing.JLabel();
        edgecombo = new javax.swing.JComboBox<>();
        edgelen = new javax.swing.JTextField();
        usmjereniradio = new javax.swing.JRadioButton();
        neusmjereniradio = new javax.swing.JRadioButton();
        emptybutton = new javax.swing.JButton();
        randombutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        randensity = new javax.swing.JTextField();
        diskbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        maxweight = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nacrtaj = new javax.swing.JButton();
        bellford = new javax.swing.JCheckBox();
        dijk = new javax.swing.JCheckBox();
        floyd = new javax.swing.JCheckBox();
        pokreni = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dijktb = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        floydtb = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bellfordbut = new javax.swing.JButton();
        querydb = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        bellfordtb = new javax.swing.JTextArea();
        nonat = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nonattb = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        startver = new javax.swing.JTextField();
        endver = new javax.swing.JTextField();
        dijkbut = new javax.swing.JButton();
        floydbut = new javax.swing.JButton();
        nonatbut = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        history = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();

        krivibroj.setBounds(new java.awt.Rectangle(200, 200, 435, 292));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("Broj vrhova mora biti između 1 i 1000!");

        javax.swing.GroupLayout krivibrojLayout = new javax.swing.GroupLayout(krivibroj.getContentPane());
        krivibroj.getContentPane().setLayout(krivibrojLayout);
        krivibrojLayout.setHorizontalGroup(
            krivibrojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(krivibrojLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        krivibrojLayout.setVerticalGroup(
            krivibrojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(krivibrojLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        brojvrhovalabel.setText("Broj vrhova");

        edgecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edgecomboActionPerformed(evt);
            }
        });

        edgelen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edgelenActionPerformed(evt);
            }
        });

        us_neus.add(usmjereniradio);
        usmjereniradio.setText("usmjereni");
        usmjereniradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usmjereniradioActionPerformed(evt);
            }
        });

        us_neus.add(neusmjereniradio);
        neusmjereniradio.setSelected(true);
        neusmjereniradio.setText("neusmjereni");
        neusmjereniradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neusmjereniradioActionPerformed(evt);
            }
        });

        emptybutton.setText("Stvori prazan graf");
        emptybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptybuttonActionPerformed(evt);
            }
        });

        randombutton.setText("Stvori slučajan graf");
        randombutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randombuttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Gustoća");

        randensity.setText("3");

        diskbutton.setText("Učitaj sa diska");
        diskbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskbuttonActionPerformed(evt);
            }
        });

        jLabel2.setText("Uredi graf:");

        jLabel3.setText("Najveća težina");

        maxweight.setText("10");

        jLabel4.setText("Neobavezno, za stvaranje slučajnog grafa");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Učitavanje grafa");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Upravljanje grafom");

        nacrtaj.setText("Nacrtaj graf");
        nacrtaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacrtajActionPerformed(evt);
            }
        });

        bellford.setText("Bellman-Ford");

        dijk.setText("Dijkstra");

        floyd.setText("Floyd-Warshall");

        pokreni.setText("Pokreni!");
        pokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokreniActionPerformed(evt);
            }
        });

        dijktb.setColumns(20);
        dijktb.setRows(5);
        jScrollPane2.setViewportView(dijktb);

        floydtb.setColumns(20);
        floydtb.setRows(5);
        jScrollPane3.setViewportView(floydtb);

        jLabel7.setText("Bellman-Ford");

        jLabel8.setText("Dijkstra");

        jLabel9.setText("Floyd-Warshall");

        bellfordbut.setText("Nacrtaj rješenje");
        bellfordbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bellfordbutActionPerformed(evt);
            }
        });

        querydb.setText("Dohvati iz baze");
        querydb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                querydbActionPerformed(evt);
            }
        });

        bellfordtb.setColumns(20);
        bellfordtb.setRows(5);
        jScrollPane4.setViewportView(bellfordtb);

        nonat.setText("Non-native");

        jLabel10.setText("Non-native (test)");

        nonattb.setColumns(20);
        nonattb.setRows(5);
        jScrollPane1.setViewportView(nonattb);

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("*obavezno");

        jLabel12.setText("Početni vrh");

        jLabel13.setText("Završni vrh");

        dijkbut.setText("Nacrtaj rješenje");
        dijkbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dijkbutActionPerformed(evt);
            }
        });

        floydbut.setText("Nacrtaj rješenje");
        floydbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floydbutActionPerformed(evt);
            }
        });

        nonatbut.setText("Nacrtaj rješenje");
        nonatbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonatbutActionPerformed(evt);
            }
        });

        history.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        history.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                historyValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(history);

        jLabel14.setText("Povijest upita");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usmjereniradio)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(edgecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(edgelen, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(brojvrhovalabel)
                                    .addGap(84, 84, 84)
                                    .addComponent(vercnt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel11))
                                .addComponent(neusmjereniradio))
                            .addGap(28, 28, 28))
                        .addComponent(jSeparator2))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(diskbutton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(emptybutton)
                                .addGap(18, 18, 18)
                                .addComponent(randombutton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3))
                                    .addGap(59, 59, 59)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(randensity, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(maxweight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(114, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nacrtaj)
                                .addComponent(dijk)
                                .addComponent(nonat)
                                .addComponent(pokreni)
                                .addComponent(bellford)
                                .addComponent(floyd)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(startver, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(endver, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(querydb)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(bellfordbut)
                            .addComponent(nonatbut)
                            .addComponent(floydbut)
                            .addComponent(dijkbut)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(neusmjereniradio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usmjereniradio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vercnt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brojvrhovalabel)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(randensity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maxweight, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emptybutton)
                            .addComponent(randombutton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(diskbutton)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edgelen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edgecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bellfordbut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nacrtaj)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(startver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(endver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bellford)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dijk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floyd)
                                .addGap(1, 1, 1)
                                .addComponent(nonat)
                                .addGap(12, 12, 12)
                                .addComponent(pokreni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(dijkbut))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(querydb)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(floydbut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nonatbut)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    int vertexnumber;
    Graph graph;
    int id;
    BellmanFordAlgorithm bfa;
    DijkstraAlgorithm da;
    FloydWarshallAlgorithm fwa;
    GraphAlgorithmTestOnly gato;
    
    private void edgelenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edgelenActionPerformed
        String text = edgelen.getText();
        try {
            int edge = Integer.parseInt(text);
            String text2 = (String) edgecombo.getSelectedItem();
            String [] razdvojen = text2.split("(?<=\\D)(?=\\d)|(?<=\\d)(?=\\D)");
            int prvi = Integer.parseInt(razdvojen[0]);
            int drugi = Integer.parseInt(razdvojen[2]);
            if (usmjereniradio.isSelected()) {
                graph.addEdge(prvi, drugi, edge);
            } else {
                graph.addEdge(prvi, drugi, edge);
                graph.addEdge(drugi, prvi, edge);
            }
        } catch (NumberFormatException nfe) {
            //what if it's not num?
        }
        
        
    }//GEN-LAST:event_edgelenActionPerformed
    

    private void edgecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edgecomboActionPerformed
        String text = (String) edgecombo.getSelectedItem();
        String [] razdvojen = text.split("(?<=\\D)(?=\\d)|(?<=\\d)(?=\\D)");
        int prvi = Integer.parseInt(razdvojen[0]);
        int drugi = Integer.parseInt(razdvojen[2]);
        edgelen.setText(String.valueOf(graph.getWeightBetween(prvi,drugi)));
    }//GEN-LAST:event_edgecomboActionPerformed

    private void emptybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptybuttonActionPerformed
        String text = vercnt.getText();
        try {
            vertexnumber=Integer.parseInt(text);
            if (vertexnumber>1000) {
                krivibroj.setVisible(true);
                return;
            }
            if (vertexnumber>50) {
                nacrtaj.setEnabled(false);
                bellfordbut.setEnabled(false);
                dijkbut.setEnabled(false);
                floydbut.setEnabled(false);
                nonatbut.setEnabled(false);
            } else {
                nacrtaj.setEnabled(true);
                bellfordbut.setEnabled(true);
                dijkbut.setEnabled(true);
                floydbut.setEnabled(true);
                nonatbut.setEnabled(true);
            }
            graph = new Graph(vertexnumber);
            Vector<String> listabridova=new Vector<>();
            if (usmjereniradio.isSelected()) {
                for (int i = 0; i<vertexnumber; i++) 
                    for (int j = 0; j<vertexnumber; j++) {
                        if (i==j) continue;
                        listabridova.add(String.valueOf(i)+"-"+String.valueOf(j));
                    }
            } else {
                for (int i = 0; i<vertexnumber; i++) 
                    for (int j = i+1; j<vertexnumber; j++)
                        listabridova.add(String.valueOf(i)+"-"+String.valueOf(j));
            }
            edgecombo.setModel(new javax.swing.DefaultComboBoxModel<>(listabridova));
            edgecomboActionPerformed(evt);   
        } catch (NumberFormatException nfe) {
            //what if it's not a num?
        }
    }//GEN-LAST:event_emptybuttonActionPerformed

    private void randombuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randombuttonActionPerformed
        String text = vercnt.getText();
        String text2 = randensity.getText();
        String text3 = maxweight.getText();
        try {
            vertexnumber = Integer.parseInt(text);
            if (vertexnumber>1000) {
                krivibroj.setVisible(true);
                return;
            }
            if (vertexnumber>50) {
                nacrtaj.setEnabled(false);
                bellfordbut.setEnabled(false);
                dijkbut.setEnabled(false);
                floydbut.setEnabled(false);
                nonatbut.setEnabled(false);
            } else {
                nacrtaj.setEnabled(true);
                bellfordbut.setEnabled(true);
                dijkbut.setEnabled(true);
                floydbut.setEnabled(true);
                nonatbut.setEnabled(true);
            }
            double density = Double.parseDouble(text2);
            int mw = Integer.parseInt(text3);
            graph = Graph.randomGraph(vertexnumber, usmjereniradio.isSelected(), density, mw);
            Vector<String> listabridova=new Vector<>();
            if (usmjereniradio.isSelected()) {
                for (int i = 0; i<vertexnumber; i++) 
                    for (int j = 0; j<vertexnumber; j++) {
                        if (i==j) continue;
                        listabridova.add(String.valueOf(i)+"-"+String.valueOf(j));
                    }
            } else {
                for (int i = 0; i<vertexnumber; i++) 
                    for (int j = i+1; j<vertexnumber; j++)
                        listabridova.add(String.valueOf(i)+"-"+String.valueOf(j));
            }
            edgecombo.setModel(new javax.swing.DefaultComboBoxModel<>(listabridova));
            edgecomboActionPerformed(evt);   
        } catch (NumberFormatException nfe) {
            //what if it's not a num?
        }
    }//GEN-LAST:event_randombuttonActionPerformed

    private void diskbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskbuttonActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String text = vercnt.getText();
            File file = fileChooser.getSelectedFile();
            try {
                vertexnumber = Integer.parseInt(text);
                if (vertexnumber>1000) {
                    krivibroj.setVisible(true);
                    return;
                }
                BufferedReader br = new BufferedReader(new FileReader(file)); 
                String line;
                int i=0;
                Vector<String> listabridova=new Vector<>();
                for (int k = 0; k<vertexnumber; k++) 
                    for (int j = 0; j<vertexnumber; j++) {
                        if (k==j) continue;
                        listabridova.add(String.valueOf(k)+"-"+String.valueOf(j));
                    }
                graph = new Graph(vertexnumber);
                while ((line = br.readLine()) != null) {
                    String[] odvojeno = line.split(" ");
                    for (int j=0; j<odvojeno.length; j++) graph.addEdge(i, j, Integer.parseInt(odvojeno[j]));
                    i++;
                }
                var usm = graph.isDirected();
                if (usm) {
                    usmjereniradio.setSelected(true);
                    neusmjereniradio.setSelected(false);
                } else {
                    usmjereniradio.setSelected(false);
                    neusmjereniradio.setSelected(true);
                }
                if (vertexnumber>50 || usm) {
                    nacrtaj.setEnabled(false);
                    bellfordbut.setEnabled(false);
                    dijkbut.setEnabled(false);
                    floydbut.setEnabled(false);
                    nonatbut.setEnabled(false);
                } else {
                    nacrtaj.setEnabled(true);
                    bellfordbut.setEnabled(true);
                    dijkbut.setEnabled(true);
                    floydbut.setEnabled(true);
                    nonatbut.setEnabled(true);
                }
                edgecombo.setModel(new javax.swing.DefaultComboBoxModel<>(listabridova));
                edgecomboActionPerformed(evt);
            } catch (IOException ex) {
                System.out.println("problem accessing file"+file.getAbsolutePath());
            } catch (NumberFormatException nfe) {
                System.out.println("File nontains nonnumbers!");
            }
        } else {
            //korisnik odustao
        }
    }//GEN-LAST:event_diskbuttonActionPerformed

    private void nacrtajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacrtajActionPerformed
        DrawGraph dg = new DrawGraph(graph);
        dg.draw();
    }//GEN-LAST:event_nacrtajActionPerformed

    private void pokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokreniActionPerformed
        id = db.insertGraph(graph);
        String text = startver.getText();
        String text2 = endver.getText();
        try {
            int start = Integer.parseInt(text);
            int end = Integer.parseInt(text2);
            if (bellford.isSelected()) {
                bfa = new BellmanFordAlgorithm(graph);
                var at1 = new AlgorithmThread(bfa,db,id,start,end,bellfordtb);
                at1.execute();
            }
            if (dijk.isSelected()) {
                da = new DijkstraAlgorithm(graph);
                var at2 = new AlgorithmThread(da,db,id,start,end,dijktb);
                at2.execute();
            }
            if (floyd.isSelected()) {
                fwa = new FloydWarshallAlgorithm(graph);
                var at3 = new AlgorithmThread(fwa,db,id,start,end,floydtb);
                at3.execute();
            }
            if (nonat.isSelected()) {
                gato = new GraphAlgorithmTestOnly(graph);
                var at4 = new AlgorithmThread(gato,db,id,start,end,nonattb);
                at4.execute();
            }
        } catch (NumberFormatException nfe) {
            //what if it's not a num?
        }
    }//GEN-LAST:event_pokreniActionPerformed

    private void bellfordbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bellfordbutActionPerformed
        var sp = bfa.getShortestPath();
        var dsp = new DrawShortestPath(graph,sp);
        db.insertShortestPath(sp, id, "BellmanFord");
        dsp.draw();
    }//GEN-LAST:event_bellfordbutActionPerformed

    private void querydbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_querydbActionPerformed
        ArrayList ids = db.selectGraphIds();
        Vector<String> listagrafova=new Vector<>();
        for (Object i: ids) {
            int j = (int) i;
            listagrafova.add("Graf "+j);
        }
        var model = new DefaultListModel();
        model.addAll(listagrafova);
        history.setModel(model);
    }//GEN-LAST:event_querydbActionPerformed

    private void dijkbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dijkbutActionPerformed
        var sp = da.getShortestPath();
        var dsp = new DrawShortestPath(graph,sp);
        db.insertShortestPath(sp, id, "Dijkstra");
        dsp.draw();
    }//GEN-LAST:event_dijkbutActionPerformed

    private void floydbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floydbutActionPerformed
        var sp = fwa.getShortestPath();
        var dsp = new DrawShortestPath(graph,sp);
        db.insertShortestPath(sp, id, "FloydWarshall");
        dsp.draw();
    }//GEN-LAST:event_floydbutActionPerformed

    private void nonatbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonatbutActionPerformed
        var sp = gato.getShortestPath();
        var dsp = new DrawShortestPath(graph,sp);
        db.insertShortestPath(sp, id, "TestOnly");
        dsp.draw();
    }//GEN-LAST:event_nonatbutActionPerformed

    private void historyValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_historyValueChanged
        String odabrano = history.getSelectedValue();
        int his_id=Integer.parseInt(odabrano.substring(5));
        Graph his_graph=db.selectGraphById(his_id);
        ArrayList<CompletedAlgorithm> his_zavrseni = db.selectCompletedAlgorithmsByGraphId(his_id);
        for(CompletedAlgorithm zavrsen: his_zavrseni) {
            switch(zavrsen.getName()) {
                case "BellmanFord":
                    bellfordtb.setText(String.valueOf(zavrsen.getTime())+" ns\r\nCijena najkraćeg puta je: "+String.valueOf(zavrsen.getResult()));
                    break;
                case "Dijkstra":
                    dijktb.setText(String.valueOf(zavrsen.getTime())+" ns\r\nCijena najkraćeg puta je: "+String.valueOf(zavrsen.getResult()));
                    break;
                case "FloydWarshall":
                    floydtb.setText(String.valueOf(zavrsen.getTime())+" ns\r\nCijena najkraćeg puta je: "+String.valueOf(zavrsen.getResult()));
                    break;
                case "TestOnly":
                    nonattb.setText(String.valueOf(zavrsen.getTime())+" ns\r\nCijena najkraćeg puta je: "+String.valueOf(zavrsen.getResult()));
                    break;
            }
        }
        id=his_id;
        graph=his_graph;
        if (his_zavrseni.size()>0) {
            startver.setText(String.valueOf(his_zavrseni.get(0).getStart()));
            endver.setText(String.valueOf(his_zavrseni.get(0).getEnd()));
        }
    }//GEN-LAST:event_historyValueChanged

    private void usmjereniradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usmjereniradioActionPerformed
        nacrtaj.setEnabled(false);
        bellfordbut.setEnabled(false);
        dijkbut.setEnabled(false);
        floydbut.setEnabled(false);
        nonatbut.setEnabled(false);
    }//GEN-LAST:event_usmjereniradioActionPerformed

    private void neusmjereniradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neusmjereniradioActionPerformed
        nacrtaj.setEnabled(true);
        bellfordbut.setEnabled(true);
        dijkbut.setEnabled(true);
        floydbut.setEnabled(true);
        nonatbut.setEnabled(true);
    }//GEN-LAST:event_neusmjereniradioActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bellford;
    private javax.swing.JButton bellfordbut;
    private javax.swing.JTextArea bellfordtb;
    private javax.swing.JLabel brojvrhovalabel;
    private javax.swing.JCheckBox dijk;
    private javax.swing.JButton dijkbut;
    private javax.swing.JTextArea dijktb;
    private javax.swing.JButton diskbutton;
    private javax.swing.JComboBox<String> edgecombo;
    private javax.swing.JTextField edgelen;
    private javax.swing.JButton emptybutton;
    private javax.swing.JTextField endver;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JCheckBox floyd;
    private javax.swing.JButton floydbut;
    private javax.swing.JTextArea floydtb;
    private javax.swing.JList<String> history;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JDialog krivibroj;
    private javax.swing.JTextField maxweight;
    private javax.swing.JButton nacrtaj;
    private javax.swing.JRadioButton neusmjereniradio;
    private javax.swing.JCheckBox nonat;
    private javax.swing.JButton nonatbut;
    private javax.swing.JTextArea nonattb;
    private javax.swing.JButton pokreni;
    private javax.swing.JButton querydb;
    private javax.swing.JTextField randensity;
    private javax.swing.JButton randombutton;
    private javax.swing.JTextField startver;
    private javax.swing.ButtonGroup us_neus;
    private javax.swing.JRadioButton usmjereniradio;
    private javax.swing.JTextField vercnt;
    // End of variables declaration//GEN-END:variables
}
