/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package najkraciputevi;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import java.util.Vector;
import javax.swing.JFileChooser;


/**
 *
 * @author winco
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        us_neus = new javax.swing.ButtonGroup();
        fileChooser = new javax.swing.JFileChooser();
        vercnt = new javax.swing.JTextField();
        brojvrhovalabel = new javax.swing.JLabel();
        edgecombo = new javax.swing.JComboBox<>();
        edgelen = new javax.swing.JTextField();
        usmjereniradio = new javax.swing.JRadioButton();
        neusmjereniradio = new javax.swing.JRadioButton();
        emptybutton = new javax.swing.JButton();
        randombutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        randensity = new javax.swing.JTextField();
        diskbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        maxweight = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nacrtaj = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        pokreni = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        brojvrhovalabel.setText("Broj vrhova");

        edgecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        edgecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edgecomboActionPerformed(evt);
            }
        });

        edgelen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edgelenActionPerformed(evt);
            }
        });

        us_neus.add(usmjereniradio);
        usmjereniradio.setSelected(true);
        usmjereniradio.setText("usmjereni");

        us_neus.add(neusmjereniradio);
        neusmjereniradio.setText("neusmjereni");

        emptybutton.setText("Stvori prazan graf");
        emptybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptybuttonActionPerformed(evt);
            }
        });

        randombutton.setText("Stvori slučajan graf");
        randombutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randombuttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Gustoća");

        randensity.setText("0.2");

        diskbutton.setText("Učitaj sa diska");
        diskbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskbuttonActionPerformed(evt);
            }
        });

        jLabel2.setText("Uredi graf:");

        jLabel3.setText("Najveća težina");

        maxweight.setText("10");

        jLabel4.setText("Neobavezno, za stvaranje slučajnog grafa");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Učitavanje grafa");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Upravljanje grafom");

        nacrtaj.setText("Nacrtaj graf");
        nacrtaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacrtajActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Algoritam1");

        jCheckBox2.setText("Algoritam2");

        jCheckBox3.setText("Algoritam3");

        pokreni.setText("Pokreni!");
        pokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokreniActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel7.setText("Algoritam1");

        jLabel8.setText("Algoritam2");

        jLabel9.setText("Algoritam3");

        jButton1.setText("Prikaži rješenje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Prikaži rješenje");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Prikaži rješenje");

        jButton4.setText("Povijest upita");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(neusmjereniradio)
                                .addComponent(usmjereniradio)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(brojvrhovalabel)
                                    .addGap(84, 84, 84)
                                    .addComponent(vercnt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(edgecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(edgelen, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(105, 105, 105))
                        .addComponent(jSeparator2))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(diskbutton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(emptybutton)
                                .addGap(18, 18, 18)
                                .addComponent(randombutton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3))
                                    .addGap(59, 59, 59)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(randensity, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(maxweight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nacrtaj)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCheckBox2)
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(pokreni)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton1)
                                .addComponent(jLabel7)
                                .addComponent(jButton2)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                .addComponent(jScrollPane4)))
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usmjereniradio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(neusmjereniradio)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vercnt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brojvrhovalabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(randensity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maxweight, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emptybutton)
                            .addComponent(randombutton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(diskbutton)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edgelen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edgecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nacrtaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox3)
                        .addGap(8, 8, 8)
                        .addComponent(pokreni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    int vertexnumber;
    Graph graph;
    
    private void edgelenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edgelenActionPerformed
        String text = edgelen.getText();
        try {
            int edge = Integer.parseInt(text);
            String text2 = (String) edgecombo.getSelectedItem();
            String [] razdvojen = text2.split("(?<=\\D)(?=\\d)|(?<=\\d)(?=\\D)");
            int prvi = Integer.parseInt(razdvojen[0]);
            int drugi = Integer.parseInt(razdvojen[2]);
            if (usmjereniradio.isSelected()) {
                graph.addEdge(prvi, drugi, edge);
            } else {
                graph.addEdge(prvi, drugi, edge);
                graph.addEdge(drugi, prvi, edge);
            }
        } catch (NumberFormatException nfe) {
            //what if it's not num?
        }
        
        
    }//GEN-LAST:event_edgelenActionPerformed
    

    private void edgecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edgecomboActionPerformed
        String text = (String) edgecombo.getSelectedItem();
        String [] razdvojen = text.split("(?<=\\D)(?=\\d)|(?<=\\d)(?=\\D)");
        int prvi = Integer.parseInt(razdvojen[0]);
        int drugi = Integer.parseInt(razdvojen[2]);
        edgelen.setText(String.valueOf(graph.getWeightBetween(prvi,drugi)));
    }//GEN-LAST:event_edgecomboActionPerformed

    private void emptybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptybuttonActionPerformed
        String text = vercnt.getText();
        try {
            vertexnumber=Integer.parseInt(text);
            graph = new Graph(vertexnumber);
            Vector<String> listabridova=new Vector<>();
            if (usmjereniradio.isSelected()) {
                for (int i = 0; i<vertexnumber; i++) 
                    for (int j = 0; j<vertexnumber; j++) {
                        if (i==j) continue;
                        listabridova.add(String.valueOf(i)+"-"+String.valueOf(j));
                    }
            } else {
                for (int i = 0; i<vertexnumber; i++) 
                    for (int j = i+1; j<vertexnumber; j++)
                        listabridova.add(String.valueOf(i)+"-"+String.valueOf(j));
            }
            edgecombo.setModel(new javax.swing.DefaultComboBoxModel<>(listabridova));
            edgecomboActionPerformed(evt);   
        } catch (NumberFormatException nfe) {
            //what if it's not a num?
        }
    }//GEN-LAST:event_emptybuttonActionPerformed

    private void randombuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randombuttonActionPerformed
        String text = vercnt.getText();
        String text2 = randensity.getText();
        String text3 = maxweight.getText();
        try {
            vertexnumber = Integer.parseInt(text);
            double density = Double.parseDouble(text2);
            int mw = Integer.parseInt(text3);
            graph = Graph.randomGraph(vertexnumber, usmjereniradio.isSelected(), density, mw);
            Vector<String> listabridova=new Vector<>();
            if (usmjereniradio.isSelected()) {
                for (int i = 0; i<vertexnumber; i++) 
                    for (int j = 0; j<vertexnumber; j++) {
                        if (i==j) continue;
                        listabridova.add(String.valueOf(i)+"-"+String.valueOf(j));
                    }
            } else {
                for (int i = 0; i<vertexnumber; i++) 
                    for (int j = i+1; j<vertexnumber; j++)
                        listabridova.add(String.valueOf(i)+"-"+String.valueOf(j));
            }
            edgecombo.setModel(new javax.swing.DefaultComboBoxModel<>(listabridova));
            edgecomboActionPerformed(evt);   
        } catch (NumberFormatException nfe) {
            //what if it's not a num?
        }
    }//GEN-LAST:event_randombuttonActionPerformed

    private void diskbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskbuttonActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String text = vercnt.getText();
            File file = fileChooser.getSelectedFile();
            try {
                vertexnumber = Integer.parseInt(text);
                BufferedReader br = new BufferedReader(new FileReader(file)); 
                String line;
                int i=0;
                Vector<String> listabridova=new Vector<>();
                for (int k = 0; k<vertexnumber; k++) 
                    for (int j = 0; j<vertexnumber; j++) {
                        if (k==j) continue;
                        listabridova.add(String.valueOf(k)+"-"+String.valueOf(j));
                    }
                graph = new Graph(vertexnumber);
                while ((line = br.readLine()) != null) {
                    String[] odvojeno = line.split(" ");
                    for (int j=0; j<odvojeno.length; j++) graph.addEdge(i, j, Integer.parseInt(odvojeno[j]));
                    i++;
                }
                edgecombo.setModel(new javax.swing.DefaultComboBoxModel<>(listabridova));
                edgecomboActionPerformed(evt);
            } catch (IOException ex) {
                System.out.println("problem accessing file"+file.getAbsolutePath());
            } catch (NumberFormatException nfe) {
                System.out.println("File nontains nonnumbers!");
            }
        } else {
            //korisnik odustao
        }
    }//GEN-LAST:event_diskbuttonActionPerformed

    private void nacrtajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacrtajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacrtajActionPerformed

    private void pokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokreniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pokreniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brojvrhovalabel;
    private javax.swing.JButton diskbutton;
    private javax.swing.JComboBox<String> edgecombo;
    private javax.swing.JTextField edgelen;
    private javax.swing.JButton emptybutton;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField maxweight;
    private javax.swing.JButton nacrtaj;
    private javax.swing.JRadioButton neusmjereniradio;
    private javax.swing.JButton pokreni;
    private javax.swing.JTextField randensity;
    private javax.swing.JButton randombutton;
    private javax.swing.ButtonGroup us_neus;
    private javax.swing.JRadioButton usmjereniradio;
    private javax.swing.JTextField vercnt;
    // End of variables declaration//GEN-END:variables
}
